include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # -------------------------
    # 스타일 / 가독성
    # -------------------------
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true

    # -------------------------
    # const / 성능
    # -------------------------
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # -------------------------
    # 안전성
    # -------------------------
    avoid_dynamic_calls: true
    unnecessary_null_checks: true
    avoid_unnecessary_containers: true

    # -------------------------
    # Clean Architecture 친화
    # -------------------------
    avoid_classes_with_only_static_members: false

    # -------------------------
    # 실무에서 거슬리는 것 제거
    # -------------------------
    public_member_api_docs: false
    lines_longer_than_80_chars: false
